import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "/src/app/globals.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <base href="{{https://harshit-vavaiya.github.io/}}" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
